In [15]:
import pandas as pd 
import numpy as np

In [30]:
df_gerentes = pd.read_excel("gerentes_lojas.xlsx")
df_vendas = pd.read_csv("vendas_tech.csv", low_memory=False)
display(df_vendas_format.sample(15))

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento
85566,85567,2023-04-27,Porto Alegre,Notebook HP,3200.0,1,Cliente_13648,3200.0
68789,68790,2023-03-16,São Paulo,Mouse Gamer,120.0,1,Cliente_27869,120.0
28139,28140,2023-03-22,Salvador,Cabo HDMI,40.0,1,Cliente_14860,40.0
86119,86120,2023-02-25,Salvador,"Monitor 27""",1200.0,1,Cliente_14949,1200.0
19124,19125,2023-10-08,Salvador,Mouse Gamer,120.0,1,Cliente_12759,120.0
53402,53403,2023-10-04,Recife,Teclado Mecânico,250.0,5,Cliente_23926,1250.0
75876,75877,2023-09-30,Salvador,Cabo HDMI,40.0,1,Cliente_8862,40.0
44324,44325,2024-07-23,Online,iPhone 14,5500.0,1,Cliente_18862,5500.0
82261,82262,2024-09-27,Salvador,Notebook Dell,3500.0,5,Cliente_12549,17500.0
73765,73766,2024-09-01,São Paulo,Teclado Mecânico,250.0,1,Cliente_18101,250.0
59107,59108,2023-05-01,Salvador,iPhone 14,5500.0,1,Cliente_1591,5500.0
12892,12893,2024-09-06,Belo Horizonte,Smartphone Samsung,2200.0,1,Cliente_9990,2200.0
52538,52539,2024-07-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_16991,5500.0
16288,16289,2024-04-23,Salvador,Notebook Dell,3500.0,1,Cliente_10418,3500.0
60745,60746,2023-02-05,Recife,Smartphone Samsung,2200.0,1,Cliente_19994,2200.0

In [ ]:
# Removendo colunas desnecessárias
df_vendas_format = df_vendas.drop(columns=['Data_Base'])

# Completando espaços vazios com o valor que não foi preenchido por erro operacional
df_vendas_format['Loja'] = df_vendas_format['Loja'].fillna('Online')

# Corrigindo o formato dos dados
df_vendas_format['Data'] = pd.to_datetime(df_vendas_format['Data'], format="%Y-%m-%d")

# Padronizando textos
df_vendas_format['Loja'] = df_vendas_format['Loja'].str.strip().str.title()

# Removendo duplicatas
df_vendas_format = df_vendas_format.drop_duplicates(subset=['ID_Pedido'])


display(df_vendas_format.sample(15))
display(df_vendas_format.info())

In [43]:
# Criar coluna de faturamento

df_vendas_format["Faturamento"] = df_vendas_format['Qtd'] * df_vendas_format["Preco_Unitario"]

# Criar coluna de forma de vendas

df_vendas_format["Forma_venda"] = np.where(df_vendas_format["Loja"] == "Online", "Online", "Presencial")

# Criar coluna que informa a região de vendas


dic_regioes = {
    'São Paulo' : 'Sudeste',
    'Belo Horizonte' : 'Sudeste',
    'Online' : 'Online',
    'Rio De Janeiro' : 'Sudeste',
    'Salvador' : 'Nordeste',
    'Recife' : 'Nordeste',
    'Curitiba' : 'Sul',
    'Porto Alegre' : 'Sul'
}

df_vendas_format['Região'] = df_vendas_format['Loja'].map(dic_regioes)

In [44]:
display(df_vendas_format)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_venda,Região
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial,Sudeste
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial,Sul
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial,Sul
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0,Presencial,Sul

In [51]:
# Analise

df_vendas_sp = df_vendas_format[df_vendas_format['Loja'] == 'São Paulo']
display(df_vendas_sp)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_venda,Região
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,40.0,Presencial,Sudeste
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,2400.0,Presencial,Sudeste
21,22,2023-11-02,São Paulo,"Monitor 27""",1200.0,1,Cliente_28539,1200.0,Presencial,Sudeste
44,45,2023-03-24,São Paulo,iPhone 14,5500.0,2,Cliente_29552,11000.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99953,99954,2024-01-02,São Paulo,Smartphone Samsung,2200.0,1,Cliente_2020,2200.0,Presencial,Sudeste
99977,99978,2023-08-19,São Paulo,Teclado Mecânico,250.0,3,Cliente_18664,750.0,Presencial,Sudeste
99987,99988,2024-08-17,São Paulo,Mouse Gamer,120.0,2,Cliente_7855,240.0,Presencial,Sudeste
99994,99995,2023-02-01,São Paulo,Teclado Mecânico,250.0,1,Cliente_22028,250.0,Presencial,Sudeste
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste