## Exercício Desafio

- Digamos que seu chefe pediu para você um relatório da análise dos salários da unidade de San Francisco da empresa. O objetivo dele é entender:

1. Qual foi a evolução do salário médio ao longo dos anos (TotalPay e TotalPayBenefits)
2. Quantos funcionários tivemos ao longo dos anos
3. Qual foi a evolução do total gasto com salário ao longo dos anos (TotalPayBenefits)

- Base de Dados a ser usada: salarios.sqlite

### Importação da Base de Dados

In [6]:
import pandas as pd
import sqlite3
conexao = sqlite3.connect('salarios.sqlite')

### Análise de Dados

In [14]:
tabela_salarios = pd.read_sql('SELECT * FROM salaries WHERE Agency = "San Francisco"', conexao)
#display(tabela_salarios)

##### 1. Qual foi a evolução do salário médio ao longo dos anos

In [19]:
tabela_sm = tabela_salarios.groupby("Year").mean(numeric_only=True)
display(tabela_sm[['TotalPay', 'TotalPayBenefits']])

          TotalPay  TotalPayBenefits
Year
2011  71744.103871      71744.103871
2012  74113.262265     100553.229232
2013  77611.443142     101440.519714
2014  75463.918140     100250.918884

##### 2. Quantos funcionários tivemos ao longo dos anos

In [23]:
media_func = tabela_salarios.groupby("Year").count()
media_func = media_func[['Id']]
media_func = media_func.rename(columns={'Id': 'Qtde'})
display(media_func)

       Qtde
Year
2011  36159
2012  36766
2013  37606
2014  38123

##### 3. Qual foi a evolução do total gasto com salário ao longo dos anos

In [26]:
def formatar(valor):
    return "${:,.2f}".format(valor)

total_pay = tabela_salarios.groupby("Year").sum(numeric_only=True)
total_pay = total_pay[['TotalPay']]
total_pay['TotalPay'] = total_pay['TotalPay'].apply(formatar)
display(total_pay)

               TotalPay
Year
2011  $2,594,195,051.88
2012  $2,724,848,200.44
2013  $2,918,655,930.80
2014  $2,876,910,951.26